"""Speaking Service — Shadowing Mode v2 with model reference audio and TTS playback.

Task 14: Model reference audio + segment metadata
- Reuses mutation tiers from ai_agent as the model reference
- Generates TTS audio for each tier using Web Speech API config
- Provides segment-level metadata for rhythm tracking

Task 1 (Phase 2): AI Examiner Chat Mode
- Conversational Speaking Part 1 & 3 simulator
- Natural follow-up questions based on user answers
- Band score estimation at session end
"""
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from shared.database import get_db

router = APIRouter(prefix="/speaking", tags=["Speaking"])


# ─────────────────────────────────────────────
#  Schemas
# ─────────────────────────────────────────────

class ShadowingModelRequest(BaseModel):
    """Request to generate model reference audio for shadowing."""
    topic: str
    part: int = 2
    accent: str = "british"  # british, american, australian
    speed: float = 0.9  # TTS rate


class SegmentMeta(BaseModel):
    """Metadata for a single speech segment."""
    segment_id: int
    text: str
    word_count: int
    duration_estimate_ms: int  # Estimated duration based on word count
    pause_after_ms: int  # Recommended pause after this segment


class TierAudioConfig(BaseModel):
    """TTS configuration for a mutation tier."""
    tier: int
    band_label: str
    target_band: float
    text: str
    key_changes: list[str]
    audio_hints: str
    segments: list[SegmentMeta]
    tts_config: dict  # lang, rate, pitch for Web Speech API


class ShadowingModelResponse(BaseModel):
    """Complete shadowing session data with model reference."""
    topic: str
    part: int
    session_id: str  # Unique session identifier
    mutation_tiers: list[TierAudioConfig]
    current_tier: int = 1  # Start at tier 1
    pass_criteria: dict  # phoneme_threshold, rhythm_threshold


# ─────────────────────────────────────────────
#  Endpoints
# ─────────────────────────────────────────────

@router.post("/shadowing/model", response_model=ShadowingModelResponse)
async def get_shadowing_model(
    request: ShadowingModelRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Generate model reference audio configuration for shadowing practice.
    
    This endpoint:
    1. Generates mutation tiers (reused from ai_agent)
    2. Splits each tier into segments for rhythm tracking
    3. Returns TTS config for frontend Web Speech API playback
    
    The frontend plays the model audio while recording the user's attempt.
    """
    # Import here to avoid circular dependency
    from services.ai_agent.main import generate_mutations, MutationGenerationRequest
    
    # Generate mutation tiers using the existing AI agent
    # For now, we'll create a simple placeholder transcript
    # In production, this would be generated by AI based on the topic
    
    base_responses = {
        1: f"Well, I think {request.topic} is quite interesting. I've been interested in it for a while now.",
        2: f"I'd like to talk about {request.topic}. It's something I've been thinking about quite a lot lately. "
           f"There are several reasons why I find this topic fascinating. "
           f"First of all, it's very relevant to my daily life. "
           f"Secondly, I believe it's an important issue that affects many people. "
           f"And finally, I think understanding {request.topic} can help us make better decisions.",
        3: f"I believe {request.topic} is a complex issue that requires careful consideration from multiple perspectives.",
    }
    
    base_transcript = base_responses.get(request.part, base_responses[2])
    
    # Generate mutations
    mutation_request = MutationGenerationRequest(
        transcript=base_transcript,
        original_band=6.0,
    )
    
    try:
        mutation_result = await generate_mutations(mutation_request)
    except Exception:
        # Fallback to generated tiers
        mutation_result = _generate_fallback_tiers(base_transcript)
    
    # Convert mutation tiers to shadowing model with segment metadata
    lang_map = {
        "british": "en-GB",
        "american": "en-US",
        "australian": "en-AU",
    }
    
    tiers_config = []
    for tier in mutation_result.tiers:
        segments = _split_into_segments(tier.text)
        
        tiers_config.append(TierAudioConfig(
            tier=tier.tier,
            band_label=tier.band_label,
            target_band=tier.target_band,
            text=tier.text,
            key_changes=tier.key_changes,
            audio_hints=tier.audio_hints,
            segments=segments,
            tts_config={
                "lang": lang_map.get(request.accent, "en-GB"),
                "rate": request.speed,
                "pitch": 1.0,
            },
        ))
    
    return ShadowingModelResponse(
        topic=request.topic,
        part=request.part,
        session_id=f"shadow-{request.part}-{hash(request.topic) % 10000}",
        mutation_tiers=tiers_config,
        current_tier=1,
        pass_criteria={
            "phoneme_threshold": 0.75,
            "rhythm_threshold": 0.70,
        },
    )


@router.get("/shadowing/session/{session_id}")
async def get_shadowing_session(
    session_id: str,
    db: AsyncSession = Depends(get_db),
):
    """
    Retrieve a shadowing session by ID.
    Used for resuming practice or reviewing past attempts.
    """
    # Placeholder — in production, this would fetch from database
    return {
        "session_id": session_id,
        "status": "active",
        "current_tier": 1,
        "attempts": [],
    }


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def _split_into_segments(text: str, max_words: int = 8) -> list[SegmentMeta]:
    """
    Split text into segments for rhythm tracking.
    Each segment is a phrase or clause that should be spoken as a unit.
    """
    words = text.split()
    segments = []
    segment_id = 0
    
    # Split on punctuation boundaries first
    import re
    # Split on sentence boundaries (. ! ?) and clause boundaries (, ; :)
    raw_segments = re.split(r'(?<=[.!?,;:])\s+', text)
    
    for raw_seg in raw_segments:
        seg_words = raw_seg.split()
        word_count = len(seg_words)
        if word_count == 0:
            continue
            
        # Estimate duration: ~150ms per word at normal speed
        duration_estimate = int(word_count * 150 / 0.9)  # Adjust for TTS rate
        pause_after = 200 if raw_seg.rstrip().endswith(('.', '!', '?')) else 100
        
        segments.append(SegmentMeta(
            segment_id=segment_id,
            text=raw_seg.strip(),
            word_count=word_count,
            duration_estimate_ms=duration_estimate,
            pause_after_ms=pause_after,
        ))
        segment_id += 1
    
    return segments


def _generate_fallback_tiers(transcript: str):
    """Generate fallback mutation tiers if AI generation fails."""
    from services.ai_agent.main import MutationGenerationResponse, MutationTier
    
    return MutationGenerationResponse(
        original_transcript=transcript,
        identified_fillers=["um", "uh"],
        tiers=[
            MutationTier(
                tier=1,
                band_label="Band 6.5 — Core",
                target_band=6.5,
                text=transcript.replace("quite", "rather").replace("think", "believe"),
                key_changes=[
                    "Upgraded vocabulary from 'think' to 'believe'",
                    "Replaced 'quite' with 'rather' for more academic tone",
                    "Removed filler words",
                ],
                audio_hints="Focus on clear word stress and steady pacing.",
            ),
            MutationTier(
                tier=2,
                band_label="Band 7.5 — Advanced",
                target_band=7.5,
                text=f"From my perspective, {transcript.lower()} Furthermore, this is an issue of considerable significance.",
                key_changes=[
                    "Added discourse marker 'From my perspective'",
                    "Restructured with formal opening",
                    "Added cohesive device 'Furthermore'",
                ],
                audio_hints="Use rising intonation for the opening phrase, then steady pacing.",
            ),
            MutationTier(
                tier=3,
                band_label="Band 8.5 — Mastery",
                target_band=8.5,
                text=f"The significance of this matter cannot be overstated. {transcript.replace('I think', 'It is my considered view that').replace('I believe', 'I am of the firm conviction that')}",
                key_changes=[
                    "Used nominalization 'The significance of'",
                    "Introduced sophisticated hedging 'It is my considered view'",
                    "Elevated register throughout",
                ],
                audio_hints="Emphasize key content words, use connected speech for natural flow.",
            ),
        ],
    )


# ─────────────────────────────────────────────
#  AI Examiner Chat Mode (Phase 2 Feature #6)
# ─────────────────────────────────────────────

class CreateExaminerSessionRequest(BaseModel):
    """Request to create a new examiner chat session."""
    part: int = 1  # IELTS Speaking part (1 or 3)
    topic: Optional[str] = None


class ExaminerChatRequest(BaseModel):
    """Request to send a message in examiner chat."""
    session_id: str
    message: str
    session_state: dict  # Serialized ExaminerSession


class ExaminerChatResponse(BaseModel):
    """Response from examiner chat."""
    session_id: str
    examiner_message: str
    follow_up_prompt: Optional[str] = None
    is_session_end: bool = False
    estimated_band: Optional[float] = None
    feedback: Optional[str] = None
    session_state: dict  # Updated session state


@router.post("/examiner/create")
async def create_examiner_session(
    request: CreateExaminerSessionRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Create a new examiner chat session.
    Returns opening message and session state.
    """
    from services.agents.examiner.agent import create_session
    
    try:
        session = create_session(part=request.part, topic=request.topic)
        
        return {
            "session_id": session.session_id,
            "part": session.part,
            "topic": session.topic,
            "opening_message": session.messages[0].content if session.messages else "",
            "session_state": session.model_dump(),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create session: {str(e)}")


@router.post("/examiner/chat", response_model=ExaminerChatResponse)
async def examiner_chat(
    request: ExaminerChatRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Send a message to the examiner and get a response.
    The examiner generates natural follow-up questions based on the student's answer.
    """
    from services.agents.examiner.agent import (
        ExaminerSession,
        process_student_response,
    )
    
    try:
        # Reconstruct session from state
        session = ExaminerSession.model_validate(request.session_state)
        
        # Process student's response
        response = await process_student_response(session, request.message)
        
        return ExaminerChatResponse(
            session_id=session.session_id,
            examiner_message=response.message,
            follow_up_prompt=response.follow_up_prompt,
            is_session_end=response.is_session_end,
            estimated_band=response.estimated_band,
            feedback=response.feedback,
            session_state=session.model_dump(),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Chat failed: {str(e)}")


@router.get("/examiner/topics")
async def get_examiner_topics():
    """Get available topics for examiner chat."""
    from services.agents.examiner.agent import ExaminerChatAgent
    
    return {
        "part1_topics": ExaminerChatAgent.PART1_TOPICS,
        "part3_topics": ExaminerChatAgent.PART3_TOPICS,
    }
