"""
Shared Pydantic schemas used across all services.

These are the canonical data contracts for:
  - Gemma 4 structured output (ExamOutput, WritingFeedback, SpeakingFeedback)
  - API request/response bodies
  - Internal service-to-service communication

Rule: BackendEvaluation is ALWAYS stripped before any response leaves the backend.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class QuestionItem(BaseModel):
    """A single question inside a QuestionGroup."""
    question_number: int
    prompt_text: str
    # For MCQ and Matching: list of options shown to the user
    local_options: Optional[List[str]] = None
    # Populated by Gemma; stripped before frontend response
    backend_evaluation: BackendEvaluation


class QuestionGroup(BaseModel):
    """A section of questions sharing a type and instructions."""
    group_id: str  # e.g. "group_1"
    question_type: str = Field(
        description=(
            "One of: TRUE_FALSE_NOT_GIVEN | MATCHING_HEADINGS | SUMMARY_COMPLETION "
            "| MULTIPLE_CHOICE | SENTENCE_COMPLETION | MATCHING_INFORMATION | FILL_BLANK"
        )
    )
    instructions: str  # e.g. "Do the following statements agree with the information..."
    questions: List[QuestionItem]


class Paragraph(BaseModel):
    """A labeled paragraph from the reading passage."""
    paragraph_id: str  # "A", "B", "C" ...
    text: str


class GenerationParams(BaseModel):
    """Parameters used when generating an exam (stored for audit/replay)."""
    difficulty: str          # beginner | intermediate | advanced | ielts_6..9
    vocabulary_level: str    # basic | medium | academic | c1 | c2
    grammar_complexity: str  # simple | medium | complex | mixed
    topic: str               # environment | science | history | technology | ...
    passage_length_words: int


class ExamOutput(BaseModel):
    """
    Top-level structured output from Gemma 4.
    Used for: reading generation, listening generation, VLM import.
    """
    title: str
    paragraphs: List[Paragraph]
    question_groups: List[QuestionGroup]
    generation_params: Optional[GenerationParams] = None


# ─────────────────────────────────────────────
#  FRONTEND-SAFE READING SCHEMAS
#  (BackendEvaluation stripped)
# ─────────────────────────────────────────────

class QuestionItemPublic(BaseModel):
    """Question sent to the frontend — no correct answer."""
    id: int                         # DB primary key
    question_number: int
    prompt_text: str
    local_options: Optional[List[str]] = None
    question_type: str
    # Adversarial trap metadata — only present on questions generated by
    # AdversarialDistractorAgent. Null for standard generated questions.
    question_evaluation: Optional[dict] = None


class QuestionGroupPublic(BaseModel):
    """Question group sent to the frontend."""
    group_id: str
    question_type: str
    instructions: str
    questions: List[QuestionItemPublic]


class GeneratedPassageResponse(BaseModel):
    """Response returned to frontend after /reading/generate or /import/reading."""
    passage_id: int
    session_id: int
    title: str
    paragraphs: List[Paragraph]          # paragraph_id + text — used for evidence highlighting
    question_groups: List[QuestionGroupPublic]
    generation_params: Optional[GenerationParams] = None
    needs_question_generation: bool = False  # True when import found no questions


# ─────────────────────────────────────────────
#  READING / LISTENING SUBMISSION SCHEMAS
# ─────────────────────────────────────────────

class AnswerSubmission(BaseModel):
    """A single user answer keyed by question DB id."""
    question_id: int
    answer: str


class QuestionTelemetryData(BaseModel):
    """Per-question behavioral telemetry captured on the frontend."""
    time_to_answer_ms: float = 0
    correction_count: int = 0
    answer_history: List[str] = []
    passage_friction_count: int = 0
    paragraph_scroll_events: List[dict] = []


class SubmitRequest(BaseModel):
    answers: List[AnswerSubmission]
    # Optional telemetry — missing field == no telemetry (backward compatible)
    telemetry: dict = {}


class QuestionExplanation(BaseModel):
    """Per-question diagnostic returned after submission analysis."""
    question_id: int
    question_number: int
    question_text: str                       # The question prompt shown to user
    question_type: str                       # TRUE_FALSE_NOT_GIVEN, MULTIPLE_CHOICE, etc.
    options: Optional[List[str]] = None      # Available options for MCQ (null for non-MCQ)
    is_correct: bool
    user_answer: str
    correct_answer: str
    evidence_text: str
    evidence_paragraph_id: str
    mistake_type: str        # Inference | Vocabulary | Distractor | Skim-Scan | None
    why_wrong: str
    correct_strategy: str
    # For listening: character index in transcript where evidence starts (for TTS jump)
    transcript_char_index: Optional[int] = None
    # Telemetry-driven confidence fields (None when telemetry disabled)
    confidence_flag: Optional[str] = None        # "low_confidence_win" | "confident_win" | None
    low_confidence_insight: Optional[str] = None  # Uma's insight text
    telemetry_summary: Optional[dict] = None      # { time_to_answer_ms, correction_count, passage_friction_count }


class SubmitAndAnalyzeResponse(BaseModel):
    session_id: int
    score: float
    total: int
    correct: int
    band_estimate: float
    results: List[QuestionExplanation]


# ─────────────────────────────────────────────
#  WRITING SCHEMAS
# ─────────────────────────────────────────────

class CriterionFeedback(BaseModel):
    """Feedback for one IELTS writing criterion."""
    criterion: str    # task_response | coherence | lexical | grammar
    band: float
    explanation: str  # 2-3 sentence explanation
    improvement_tip: str


class InlineCorrection(BaseModel):
    """An inline grammar/vocabulary correction."""
    incorrect: str
    correct: str
    explanation: str
    error_type: str   # grammar | vocabulary | punctuation | spelling
